/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Graph: typeof import('./src/components/Graph.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ScenarioGraphs: typeof import('./src/components/ScenarioGraphs.vue')['default']
    ScenarioInputs: typeof import('./src/components/ScenarioInputs.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
  }
}
