export default {
  "__model_name": "My Model",
  "graph_001_title": "Pop",
  "graph_002_title": "GDP",
  "graph_003_title": "GDPperCap",
  "graph_004_title": "StockLV",
  "graph_005_title": "StockLocomotive",
  "graph_006_title": "StockBuilding",
  "graph_dataset_label__gdpchina": "GDPChina",
  "graph_dataset_label__gdppercapchina": "GDPperCapChina",
  "graph_dataset_label__gdppercapobschina": "GDPperCapObsChina",
  "graph_dataset_label__lvobschina": "LVObsChina",
  "graph_dataset_label__popchina": "PopChina",
  "graph_dataset_label__popobschina": "PopObsChina",
  "graph_dataset_label__stockbuilding": "StockBuilding",
  "graph_dataset_label__stockbuildingobs": "StockBuildingObs",
  "graph_dataset_label__stocklocolog": "StockLocoLOG",
  "graph_dataset_label__stocklocoobs": "StockLocoObs",
  "graph_dataset_label__stocklocotrue": "StockLocoTrue",
  "input_001_label": "ChangeGDPpercapSat[China]",
  "input_002_label": "ChangePopSat[China]",
  "input_003_label": "StockHighSpeed2015[China]",
  "input_group_title__sliders": "Sliders",
  "input_units__units": "(units)"
}